name: Scala CI with Coveralls

on:
  push:
    branches: [ "CI-Coveralls" ]
  pull_request:
    branches: [ "CI-Coveralls" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile
        run: sbt compile

  run_tests_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Project and Export Coverage
        env:
          COVERALLS_REPO_TOKEN: ${ secrets.COVERALLS_REPO_TOKEN }
        run: |
          export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          sbt clean;
          sbt test;
          sbt coverage;
          sbt coverageReport;
